In [ ]:
#PYTHON NUMPY ARRAYS BASICS

In [13]:
import numpy as np
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
arr.ndim

1

In [15]:
arr.shape

(4,)

In [16]:
arr.nbytes

16

In [18]:
arr[-1]

4

In [22]:
sliced = arr[0:2:1].copy() #x[start:stop:step]
sliced

array([1, 2])

In [21]:
arr

array([1, 2, 3, 4])

In [ ]:
#RESHAPING AND CONCATENATION

In [23]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# arr1.reshape(arr1, (3,2))

In [26]:
arr2 = np.array([[0,9,8], [7,6,5]])
np.concatenate(arr2)

array([0, 9, 8, 7, 6, 5])

In [29]:
x = [1,2]
y = [3,4]
np.vstack((x,y))

array([[1, 2],
       [3, 4]])

In [30]:
np.hstack((x,y))

array([1, 2, 3, 4])

In [31]:
arr3 = np.array([[1,2], [3,4], [5,6]])   #SPLITTING
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.vsplit(arr3, 3)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [37]:
np.hsplit(arr3, 2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [ ]:
#COMPUTATIONS AND AGGREGATIONS

In [39]:
np.std(arr3)

1.707825127659933

In [41]:
np.amax(arr3)

6

In [45]:
#Create a null vector (all zeros) of size 10 and set it in the variable called “Z”.
# Your solution goes here (Z = ....)
Z = np.array([0,0,0,0,0,0,0,0,0,0])
#Z = np.zeros(10)

In [ ]:
#Create a 1D array of numbers from 0 to 9 and set it in the variable called “arr”.
# Your solution goes here
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
#Create a 3x3x3 array with random values and set it in the variable called “arr”.
arr = np.random.random((3,3,3))

In [ ]:
#Create a 10x10 array with random values called “arr4”. Find its minimum and maximum values and set them in the variables called “min_val” and “max_val” respectively.
arr4 = np.random.random((10,10))
min_val = np.min(arr4)
max_val = np.max(arr4)

In [ ]:
#First create a 1D array with numbers from 1 to 9 and then convert it into a 3x3 grid. Store the final answer in the variable called “grid”
grid = np.arange(1,10).reshape((3,3))

In [ ]:
#Replace the maximum value in the given vector, “arr6”, with -1.
arr6 = np.arange(10)
max_val = np.max(arr6)
arr6[max_val] = -1

In [ ]:
# Reverse the rows of the given 2D array, “arr7”.
arr7 = np.arange(9).reshape(3,3)
arr7 = arr7[::-1]

In [ ]:
#Subtract the mean of each row of the given 2D array, “arr8”, from the values in the array. Set the updated array in “transformed_arr8”.
arr8 = np.random.rand(3, 10)
transformed_arr8 =  arr8 - arr8.mean(axis=1, keepdims=True)